BoS Timelocks +2 Knight Slots for SK/K, Add Ripper & BPF
LoneStarF13/LoneStar pull request #142
Opened 2022-01-05 02:13 UTC by Cythisiax

increases BoS timelocks nicely

Knight/Scribe: 10 hours
Senior: 30 hours
Head Knight/Scribe: 50 hours
Paladin: 40 hours
Head Paladin: 80 hours

Adds Ripper & BPF to JK/K and SK. 

+1 Knight slot
+1 Senior Knight slot

2022-01-05 14:38 UTC, AdamElTablawy commented
approved

2022-01-06 16:46 UTC, OneOneThreeEight requested changes

2022-01-06 16:46 UTC, OneOneThreeEight commented on code/modules/jobs/job_types/bos.dm
> +		/obj/item/melee/powered/ripper/prewar,
/obj/item/melee/powered/ripper/prewar = 1,

2022-01-06 16:46 UTC, OneOneThreeEight commented on code/modules/jobs/job_types/bos.dm
> +		/obj/item/shield/riot/bullet_proof,
/obj/item/shield/riot/bullet_proof = 1,

2022-01-06 16:46 UTC, OneOneThreeEight commented on code/modules/jobs/job_types/bos.dm
> +		/obj/item/melee/powered/ripper/prewar,
/obj/item/melee/powered/ripper/prewar = 1,

2022-01-06 16:46 UTC, OneOneThreeEight commented on code/modules/jobs/job_types/bos.dm
> +		/obj/item/shield/riot/bullet_proof,
/obj/item/shield/riot/bullet_proof = 1,

2022-01-06 16:46 UTC, OneOneThreeEight commented on code/modules/jobs/job_types/bos.dm
> +		/obj/item/melee/powered/ripper/prewar,
/obj/item/melee/powered/ripper/prewar = 1,

2022-01-06 16:46 UTC, OneOneThreeEight commented on code/modules/jobs/job_types/bos.dm
> +		/obj/item/shield/riot/bullet_proof,
/obj/item/shield/riot/bullet_proof = 1,

2022-01-07 14:07 UTC, merged