stim fix
LoneStarF13/LoneStar pull request #18
Opened 2021-12-19 06:37 UTC by AdamElTablawy

fixes stim

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

:cl:
tweak: fixes stims
/:cl:

2021-12-20 11:18 UTC, buffyuwu commented
oh you- made a whole new PR close the other lol

2021-12-22 19:44 UTC, AdamElTablawy commented
its testmergable again @buffyuwu

2021-12-23 22:22 UTC, buffyuwu requested changes

2021-12-23 22:22 UTC, buffyuwu commented on code/modules/fallout/reagents/medicines.dm
>  	metabolization_rate = 0.5 * REAGENTS_METABOLISM
this should be higher

2021-12-23 22:24 UTC, buffyuwu commented on code/modules/fallout/reagents/medicines.dm
>  	metabolization_rate = 0.5 * REAGENTS_METABOLISM
```suggestion
	metabolization_rate = 5 * REAGENTS_METABOLISM
```

2021-12-24 09:55 UTC, closed without merging