oasis prepares for war
LoneStarF13/LoneStar pull request #185
Opened 2022-01-14 05:44 UTC by cornercube

## About The Pull Request

ports the merc heavy helmet into oasis, as the heavy steel helmet and the heavy steel breastplate (sprite pending)
has an amazing T5 protection vs bullets, but only T4 against melee, and still only T3 against lasers
a unique craftable that makes use of pre-war alloys to increase resistance vs high speed projectiles
due to low body coverage, it is poor against melee attacks

adds recipes for police pistol and police rifle, shopkeep and sheriff know it by default, a citizen loadout gets a book that teaches it to them

## Why It's Good For The Game
gives oasis more unique gear
gives them very specialized anti-bullet gear
shame to watch all the fortune13 gear go to waste

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: heavy steel armor
add: recipes
add: a new book to teach the recipes

/:cl:

2022-01-15 16:15 UTC, Sinbest commented
![image](https://user-images.githubusercontent.com/84290420/149629100-984106e8-1e30-479a-b595-792b3ae42140.png)

2022-01-15 16:19 UTC, cornercube commented
> ![image](https://user-images.githubusercontent.com/84290420/149629100-984106e8-1e30-479a-b595-792b3ae42140.png)

i just thought the helmet looked cool, and i wanted to steer gear more towards specialization

2022-01-18 13:13 UTC, OneOneThreeEight requested changes
Changes may later require tweaking alongside the linearmor PR.

2022-01-18 13:13 UTC, OneOneThreeEight commented on code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
> +	result = /obj/item/gun/ballistic/automatic/rangemaster
needs to be "/obj/item/gun/ballistic/automatic/marksman/policerifle"

2022-01-19 01:17 UTC, cornercube commented on code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
> +	result = /obj/item/gun/ballistic/automatic/rangemaster
fixed

2022-01-22 02:04 UTC, merged