veteran ranger buff pr (shotgun loadout)
LoneStarF13/LoneStar pull request #292
Opened 2022-02-01 10:57 UTC by lolman360

## About The Pull Request

vet ranger shotgun loadout

## Why It's Good For The Game

req

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: vet ranger shotgun loadout
/:cl:

2022-02-02 03:59 UTC, Snoozer000 commented
Arent rangers suppose to have a focus on long range advantage? With an emphasis on revolvers and rifles? Wouldnt this negate legions close range advantage?

2022-02-02 08:23 UTC, AllCorruptingWyrm commented
> 

a few staff seemed to be for it and note that in the games, vet rangers did have riot shotguns as well.
Compare it to the other loadouts, those being the amr (useful only if you join mid round,). the brush gun which is two .45-75 guns, and the gunslinger which breaks lore with no seqoia.

2022-02-03 22:28 UTC, OneOneThreeEight requested changes

2022-02-03 22:28 UTC, OneOneThreeEight commented on code/modules/jobs/job_types/ncr.dm
> +		/datum/outfit/loadout/shotter //Riot shotty, Sequoia
/datum/outfit/loadout/shotgunner

2022-02-03 22:28 UTC, OneOneThreeEight commented on code/modules/jobs/job_types/ncr.dm
> +/datum/outfit/loadout/shotter
/datum/outfit/loadout/shotgunner

2022-02-03 22:28 UTC, OneOneThreeEight commented on code/modules/jobs/job_types/ncr.dm
> +	name = "Veteran Shotter"
name = "Veteran Ranger Shotgunner"

2022-02-04 13:34 UTC, Looreydev commented on code/modules/jobs/job_types/ncr.dm
> +		/obj/item/ammo_box/c4570 = 1,
The comma isn't needed at the end of lists but that's just a next-level petty complaint from me at this point lol
```suggestion
		/obj/item/ammo_box/c4570 = 1
```

2022-02-05 15:54 UTC, merged