show your love for nuka cola
LoneStarF13/LoneStar pull request #310
Opened 2022-02-04 05:30 UTC by cornercube

## About The Pull Request
adds a trait that allows you to sense and derive pleasure from the act of drinking cola and hate healthy foods
adds a new flavor, NUKA

## Why It's Good For The Game
because nuka cola is so good, you can get addicted to it in FO1 and 2
adds more utility to nuka cola products as well

feel free to add sunset somewhere down the line which makes you hate NUKA

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: new flavor NUKA
add: NUKA flavor to nuka-cola and variants
trait: nuka fiend, which causes you to gain mood from drinking nuka cola and lose mood from heating fruits 

/:cl:

2022-02-04 20:39 UTC, Looreydev requested changes

2022-02-04 20:39 UTC, Looreydev commented on code/datums/traits/good.dm
> +	name = "Nuka Fiend"
```suggestion
	name = "Nuka Friend"
```

2022-02-05 13:15 UTC, cornercube commented on code/datums/traits/good.dm
> +	name = "Nuka Fiend"
Fiend is intentional, as per CRANKs suggestion

2022-02-09 01:10 UTC, lolman360 commented on code/modules/fallout/reagents/drinks.dm
> +	else
you can remove this entire else it doesnt do anything
```suggestion
```

2022-02-09 01:10 UTC, lolman360 commented on code/datums/traits/good.dm
> +	species.disliked_food |= FRUIT
make them dislike vegetables instead  it'd be funnier
```suggestion
	species.disliked_food |= VEGETABLES
```

2022-02-11 02:23 UTC, merged