Legion Boogaloo 2: Gunslinger Vexilaloo
LoneStarF13/LoneStar pull request #315
Opened 2022-02-05 03:08 UTC by SeniorScore

## About The Pull Request

Adds funny gunslinger vex loadout and nightstalker vex helmet (from DR2). I wanted a corgi vex helmet yet here we are.

## Why It's Good For The Game

Dual Colt SAAs go BR-BR-BR

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
/:cl:

2022-02-05 05:49 UTC, SeniorScore commented
ADDS IMMUNES, LEGION CAMP-DUTY ROLE, NOW TOO I GUESS. DEATH TO SLAVEMASTER

2022-02-06 20:16 UTC, Jawnner commented
Gunslinger loadout is eh and doesn't really fit Legion like that. I'd replace the dual SAAs w/ a Marksman Carbine and a .357 revolver.

Replace the Mountain Bear pistol with a lever-action and buckshot shells, keep ripper

Replace Desert Fox 10mm w/ grease gun, .44 revolver

Give the Prime Dec the assault carbine and a scope underneath leads from the rear loadout

2022-02-07 07:12 UTC, SeniorScore commented
Dumped the Vex loadout changes, nightstalker helmet is still in, unused is all.

Immunes should be ready to roll though.

2022-02-07 22:19 UTC, Looreydev requested changes

2022-02-07 22:19 UTC, Looreydev commented on code/__DEFINES/jobs.dm
> +#define F13IMMUNE		(1<<15)
```suggestion
#define F13IMMUNE	(1<<15)
```

2022-02-07 22:19 UTC, Looreydev commented on code/modules/jobs/job_types/legion.dm
> +	head = null
```suggestion
```

2022-02-07 22:19 UTC, Looreydev commented on code/modules/jobs/job_types/legion.dm
> +	r_pocket = null
```suggestion
```

2022-02-07 22:19 UTC, Looreydev commented on code/modules/jobs/job_types/legion.dm
> +		/obj/item/reagent_containers/pill/patch/healingpowder = 2,
```suggestion
		/obj/item/reagent_containers/pill/patch/healingpowder = 2
```

2022-02-07 22:21 UTC, Looreydev requested changes

2022-02-07 22:21 UTC, Looreydev commented on code/__DEFINES/jobs.dm
>  #define F13AUXILIA		(1<<13)
```suggestion
#define F13AUXILIA	(1<<13)
```

2022-02-07 22:42 UTC, Looreydev approved these changes

2022-02-10 01:26 UTC, merged