an explosion pr that doesn't break
LoneStarF13/LoneStar pull request #35
Opened 2021-12-23 12:48 UTC by AdamElTablawy

Explosions are less deadly and won't gib anymore. Still very deadly, but they shouldn't instakill, will rarely delimb, and will throw you from the target impact zone. They also don't KO.

This lets me PR actual bomb weapons and grenades.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

:cl:
balance: explosions no longer gib, are less likely to delimb, and throw you from the target impact zone.
/:cl:

2021-12-23 22:06 UTC, buffyuwu requested changes

2021-12-23 22:06 UTC, buffyuwu commented on code/modules/mob/living/carbon/human/human_defense.dm
> +				/*for(var/I in contents)
this only damages them now if they have armor thats higher than the gib threshold :) see the else?

2021-12-23 22:06 UTC, buffyuwu commented on code/modules/mob/living/carbon/human/human_defense.dm
>  			else
comment this and the return above it,- hell just comment from the if(bomb_armor and indent the damage code back out of its space

2021-12-24 22:21 UTC, AdamElTablawy commented on code/modules/mob/living/carbon/human/human_defense.dm
>  			else
noted will fix

2021-12-26 21:47 UTC, AdamElTablawy commented
fixed a while ago

2022-01-01 03:20 UTC, merged