The Great Tribal Rework WIP
LoneStarF13/LoneStar pull request #45
Opened 2021-12-24 21:50 UTC by Tokorizo

## About The Pull Request
The tribe is a flawed faction that I have given hundreds of hours playing to, It one of the most unique playstyles in the game but it constantly suffers flaws and errors due to whoever I'm running the faction. Be it the in-game leadership or just whoever maintains it. It always has problems and these problems have stemmed since DR in its creation to be a ERP faction by Zyy.

The removal of the tribe will pave a new role for people to try out called Tribal. 

Similar to Wastelander or Outlaw, Tribals start as neutral that have no ties or connections to any factions, they have the ability to form their own tribes similar to gangs and create IC diplomatic interactions. Playable solo or in a group.

In order to make them different from Outlaws and Wasters, they are given restrictions which include the ability and struggle to use certain workbenches like ammo and workshops. However, they have the ability to craft their own role-exclusive items with mob drops, unlocking a lot of the old tribal exclusive items more for the general player base to use.

## Why It's Good For The Game

More player freedom (WIP)

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2021-12-25 14:24 UTC, OneOneThreeEight commented
interesting, will be tracking how this goes.

2021-12-26 03:10 UTC, Tokorizo commented
>4 errors

![image](https://user-images.githubusercontent.com/62493359/147397959-98568745-6bea-49cc-930d-9a9a66a63ecd.png)

2021-12-28 00:56 UTC, Tokorizo commented
Right, this should be ready for testing now.

2021-12-28 01:17 UTC, Kapu1178 commented on code/modules/jobs/job_types/wasteland.dm
> +	H.mind.teach_crafting_recipe(/datum/crafting_recipe/tribalwar/spearquiver)
Store all of these in a list and just do

for(var/datum/crafting_recipe/recipe as() in list)
   H.mind.teach_crafting_recipe(recipe)

2021-12-28 13:31 UTC, OneOneThreeEight commented on code/modules/jobs/job_types/wasteland.dm
> +	H.mind.teach_crafting_recipe(/datum/crafting_recipe/tribalwar/spearquiver)
Agreed, makes the code a bit cleaner.

2021-12-29 14:10 UTC, cornercube commented
i still think that the tribals should start out in a common zone instead of interspersed like wastelanders, to encourage tribals to stick together

2021-12-29 17:05 UTC, Neveralone1744 commented
id like to see a common area too. we even already picked a small spot that could work for us. a tribe scattered is a tribe dead

2021-12-29 21:14 UTC, Doru-7 commented
In response to the fact that an 80 pop round happened with no one playing tribal, there's a few key reasons for that. 
The first is that there's so much lore and mechanical specialization that's entirely original and not based on anything existing in fallout. This makes it hard for someone interested in playing as a tribal to play without having a wiki page open at all times.
The second is that all the players who played tribal characters and understood what they were have either wrapped up their stories with those characters and left the region, or straight up dropped those characters under the premise that the Legion have wiped them out. This is because they were kindly given several weeks of notice that the tribe would soon no longer exist, so they made their peace and left.
The third, and most troubling, is that the people who remain in the tribe(with the exception of a few veteran players who are still telling their stories to the very end.) are new players, with their own unique reasons for playing as a tribal. They no longer have guidance from veteran tribe players, meaning they can't learn the unique laws, traditions, and rituals in a natural manner. A few of these new players have even taken advantage of their faction's neutral stance to engage in TDM with the more populated factions, creating a small but significant sense of hostility towards the tribe as a whole.

This is all to say that Tribals are set on a precariously thin rope, and we who care about the tribes have to do our best to make sure it functions in a way that will ensure its survival. Therefore, I have two suggestions to add to this PR:
1. A common spawn location, so tribal players can group up easier. My recommendation is the tent and campfire at the end of the road that leads to the vault museum tileset, directly south of Oasis. The only issue is that it's a semi-common place for players to create settlements that may trap any new players that spawn in.
2. Book Binders and digital library. These are currently being used in the Brotherhood's base, but would benefit tribals who can find them if they appear in more places in the general wasteland. This is because the Wayfarers relied on oral tradition to teach new members. If a tribe of the future is to survive, they'll need written tradition as well. This means that all the lore associated with the tribes, be that the gods and traditions of the old Wayfarers, or the scribblings of the new tribes to come, will be easily accessible in a natural manner, and will even be available for outsiders to learn from.(Which also gives the Brotherhood scribes a reason to read books in the library, since new and functional books will be coming in.)

TL;DR: Tribals want to stick together. Common spawn area and the ability to write books will be a huge help.

2021-12-30 02:39 UTC, OneOneThreeEight requested changes
Address merge conflicts, please.

2021-12-30 16:02 UTC, OneOneThreeEight requested changes

2021-12-30 16:02 UTC, OneOneThreeEight commented on code/modules/jobs/job_types/tribals.dm
> +//Commented out for now
un-comment these out, please, they are messing with the ghost role spawners. jobs with 0 slots will never show up to the playerbase anyway

2022-01-01 03:20 UTC, merged