stim fix for frok
LoneStarF13/LoneStar pull request #9
Opened 2021-12-18 02:48 UTC by cornercube

## About The Pull Request

porting one of froks balance changes
prevents stim stacking

## Why It's Good For The Game

prevents stim stacking

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

el bug fix
/:cl:

2021-12-18 07:17 UTC, buffyuwu commented on code/modules/fallout/reagents/medicines.dm
> +/datum/reagent/medicine/stimpakimitation
why are we shortening this path?

2021-12-18 07:18 UTC, buffyuwu commented
also if you're porting something please link to the original PR

2021-12-18 10:55 UTC, cornercube commented on code/modules/fallout/reagents/medicines.dm
> +/datum/reagent/medicine/stimpakimitation
de-subtyped to prevent them from stacking

2021-12-18 22:33 UTC, buffyuwu commented on code/modules/fallout/reagents/medicines.dm
> +/datum/reagent/medicine/stimpakimitation
when you say stacking, are you referring to holding more in the same 'stack' or mechanically combat stimming repeatedly?

2021-12-18 23:07 UTC, AdamElTablawy commented on code/modules/fallout/reagents/medicines.dm
> +/datum/reagent/medicine/stimpakimitation
stacking as in pathing a reagent as a subtype resulted in the effects 'stacking'

it became stimpak/imitation and so imitation stimpaks and regular stimpaks would both stack, healing 6.5

same with super stims, they healed 12.5 instead of the expected 8, due to path stacking

i attempted to do a heal_amount var instead but it had the same issue

2021-12-20 11:17 UTC, buffyuwu commented on code/modules/fallout/reagents/medicines.dm
> +/datum/reagent/medicine/stimpakimitation
please fix the right way:tm: instead of repathing needlessly as we discussed


thank you!!!

2021-12-20 11:18 UTC, buffyuwu requested changes
let me know when you've corrected this via pinging me in discord

2021-12-24 14:21 UTC, OneOneThreeEight commented
better implementation to unparent the stim derivatives assdsddghsj

2021-12-25 08:26 UTC, merged